version: "3.7"

services:

  crash-detection:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/:ro
    tty: true
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - WEB_CONCURRENCY=2  # Maximum number of workers
